# SPARCED-1.4
# Last update: 2025-02-19


# General infos
name: "SPARCED"
header: "Erdem et al., Nat Commun 2022"
location: "input_files"
user: " Jonah R. Huggins"

# Compilation
compilation:
    directory: "input_files"
    files:
      compartments: "Compartments.txt"
      output_parameters: "output_parameters.txt"  # This file is generated upon compilation
      ratelaws: "Ratelaws.txt"
      species: "standard_Species.txt"

# Experiment settings
simulation:
  model: 
    amici: "jupyter_notebooks/SPARCED"
    sbml: "jupyter_notebooks/SPARCED.xml"
  population_size: 1
  verbose: True
  exchange: 30
  data:
    gene_regulation: "GeneReg.txt"
    omics: "OmicsData.txt"

  # Protocol steps
  protocol:
    name: "Experiment_1-Default"
    hybrid: True
    duration: 24.0
    perturbations: 
      parameters: {}
      species: {'E': 0.0, 'INS': 0.0}


  # Individual Model Exceptions
  Exceptions:
    omics:
      kGac: {'Ce': 0.0} # Placeholder
    gene_regulation:
      kGac: {'Ce': 0.0} # Placeholder
  
  results:
    filename: "Experiment_1-results"
    directory: "results"

