name: sparced
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - binutils_impl_linux-64=2.38
  - binutils_linux-64=2.38.0
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - gcc_impl_linux-64=11.2.0
  - gcc_linux-64=11.2.0
  - gxx_impl_linux-64=11.2.0
  - gxx_linux-64=11.2.0
  - kernel-headers_linux-64=2.6.32
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-devel_linux-64=11.2.0
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libopenblas=0.3.21
  - libstdcxx-devel_linux-64=11.2.0
  - libstdcxx-ng=13.2.0
  - libuuid=1.41.5
  - libzlib=1.2.13
  - mpi=1.0
  - ncurses=6.4
  - nomkl=3.0
  - openblas=0.3.21
  - openblas-devel=0.3.21
  - openmpi-mpicc=4.1.5
  - openssl=3.1.3
  - pip=23.2.1
  - python=3.11.5
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - sysroot_linux-64=2.12
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - amici==0.16.1
      - antimony==2.12.0.2
      - asttokens==2.2.1
      - attrs==22.2.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bleach==6.0.0
      - colorama==0.4.6
      - comm==0.1.3
      - contourpy==1.0.7
      - cycler==0.11.0
      - debugpy==1.6.7
      - decorator==5.1.1
      - defusedxml==0.7.1
      - et-xmlfile==1.1.0
      - executing==1.2.0
      - fastjsonschema==2.16.3
      - fonttools==4.39.3
      - h5py==3.8.0
      - ipykernel==6.22.0
      - ipython==8.12.0
      - jdata==0.5.3
      - jedi==0.18.2
      - jinja2==3.1.2
      - jsonschema==4.17.3
      - jupyter-client==8.1.0
      - jupyter-core==5.3.0
      - jupyterlab-pygments==0.2.2
      - kiwisolver==1.4.4
      - markupsafe==2.1.2
      - matplotlib==3.7.1
      - matplotlib-inline==0.1.6
      - mistune==2.0.5
      - mpi4py==3.1.4
      - mpmath==1.3.0
      - nbclient==0.7.4
      - nbconvert==7.3.1
      - nbformat==5.8.0
      - nest-asyncio==1.5.6
      - numpy==1.23.2
      - openmpi==0.0.1
      - openpyxl==3.1.2
      - packaging==23.1
      - pandas==1.5.3
      - pandocfilters==1.5.0
      - parso==0.8.3
      - petab==0.1.29
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - pkgconfig==1.5.5
      - platformdirs==3.2.0
      - prompt-toolkit==3.0.38
      - psutil==5.9.4
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pygments==2.15.0
      - pyparsing==3.0.9
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - python-libsbml==5.20.0
      - pytz==2023.3
      - pyyaml==6.0
      - pyzmq==25.0.2
      - scipy==1.10.1
      - seaborn==0.12.2
      - six==1.16.0
      - soupsieve==2.4.1
      - stack-data==0.6.2
      - swig==4.1.1
      - sympy==1.11.1
      - tinycss2==1.2.1
      - toposort==1.10
      - tornado==6.2
      - traitlets==5.9.0
      - tzdata==2023.3
      - wcwidth==0.2.6
      - webencodings==0.5.1
      - wurlitzer==3.0.3
      - xlrd==2.0.1
