#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jan 14 13:10:35 2022

@author: arnab
"""
import argparse

from mpi4py import MPI
# from numpy import random

from mpi4py.futures import MPICommExecutor

rank = MPI.COMM_WORLD.Get_rank()

# print("hello from rank", rank)

parser = argparse.ArgumentParser()

parser.add_argument('--sim_name', metavar='sim_name', help='Enter name of the experiment', default = "lapatinib_drs_test_mpi99")

args = parser.parse_args()

sim_name = str(args.sim_name)

def f(x):
    # print("hello from rank", rank)
    # return x**2
    return str(f"result from rank {rank} for sim name {sim_name} = {x**2}")

# random.seed()

# y = random.randint(0,999)
with MPICommExecutor(MPI.COMM_WORLD, root=0) as executor:
    for result in executor.map(f,range(10)):
        print(result)


# my_start = rank
# my_end = rank*4

# for i in range(my_start, my_end):
#     result = f(i)
#     print(f"[rank {rank}]: f({i}) = {result}")
    
# print(f"random number generated by rank {rank} is {y}")

# print(f"random number generated is {y}")

#%%

